/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AlunosRouteImport } from './routes/alunos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlunosAlunoIdRouteImport } from './routes/alunos.$alunoId'

const AlunosRoute = AlunosRouteImport.update({
  id: '/alunos',
  path: '/alunos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlunosAlunoIdRoute = AlunosAlunoIdRouteImport.update({
  id: '/$alunoId',
  path: '/$alunoId',
  getParentRoute: () => AlunosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alunos': typeof AlunosRouteWithChildren
  '/alunos/$alunoId': typeof AlunosAlunoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alunos': typeof AlunosRouteWithChildren
  '/alunos/$alunoId': typeof AlunosAlunoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alunos': typeof AlunosRouteWithChildren
  '/alunos/$alunoId': typeof AlunosAlunoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/alunos' | '/alunos/$alunoId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/alunos' | '/alunos/$alunoId'
  id: '__root__' | '/' | '/alunos' | '/alunos/$alunoId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlunosRoute: typeof AlunosRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/alunos': {
      id: '/alunos'
      path: '/alunos'
      fullPath: '/alunos'
      preLoaderRoute: typeof AlunosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alunos/$alunoId': {
      id: '/alunos/$alunoId'
      path: '/$alunoId'
      fullPath: '/alunos/$alunoId'
      preLoaderRoute: typeof AlunosAlunoIdRouteImport
      parentRoute: typeof AlunosRoute
    }
  }
}

interface AlunosRouteChildren {
  AlunosAlunoIdRoute: typeof AlunosAlunoIdRoute
}

const AlunosRouteChildren: AlunosRouteChildren = {
  AlunosAlunoIdRoute: AlunosAlunoIdRoute,
}

const AlunosRouteWithChildren =
  AlunosRoute._addFileChildren(AlunosRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlunosRoute: AlunosRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
