/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardPersonalExerciciosRouteImport } from './routes/dashboard.personal.exercicios'
import { Route as DashboardPersonalAgendaRouteImport } from './routes/dashboard.personal.agenda'
import { Route as DashboardPersonalAlunosIndexRouteImport } from './routes/dashboard.personal.alunos.index'
import { Route as DashboardPersonalAlunosAlunoIdRouteImport } from './routes/dashboard.personal.alunos.$alunoId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPersonalExerciciosRoute =
  DashboardPersonalExerciciosRouteImport.update({
    id: '/dashboard/personal/exercicios',
    path: '/dashboard/personal/exercicios',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardPersonalAgendaRoute = DashboardPersonalAgendaRouteImport.update({
  id: '/dashboard/personal/agenda',
  path: '/dashboard/personal/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPersonalAlunosIndexRoute =
  DashboardPersonalAlunosIndexRouteImport.update({
    id: '/dashboard/personal/alunos/',
    path: '/dashboard/personal/alunos/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardPersonalAlunosAlunoIdRoute =
  DashboardPersonalAlunosAlunoIdRouteImport.update({
    id: '/dashboard/personal/alunos/$alunoId',
    path: '/dashboard/personal/alunos/$alunoId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard/personal/agenda': typeof DashboardPersonalAgendaRoute
  '/dashboard/personal/exercicios': typeof DashboardPersonalExerciciosRoute
  '/dashboard/personal/alunos/$alunoId': typeof DashboardPersonalAlunosAlunoIdRoute
  '/dashboard/personal/alunos/': typeof DashboardPersonalAlunosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/personal/agenda': typeof DashboardPersonalAgendaRoute
  '/dashboard/personal/exercicios': typeof DashboardPersonalExerciciosRoute
  '/dashboard/personal/alunos/$alunoId': typeof DashboardPersonalAlunosAlunoIdRoute
  '/dashboard/personal/alunos': typeof DashboardPersonalAlunosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard/personal/agenda': typeof DashboardPersonalAgendaRoute
  '/dashboard/personal/exercicios': typeof DashboardPersonalExerciciosRoute
  '/dashboard/personal/alunos/$alunoId': typeof DashboardPersonalAlunosAlunoIdRoute
  '/dashboard/personal/alunos/': typeof DashboardPersonalAlunosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard/personal/agenda'
    | '/dashboard/personal/exercicios'
    | '/dashboard/personal/alunos/$alunoId'
    | '/dashboard/personal/alunos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/personal/agenda'
    | '/dashboard/personal/exercicios'
    | '/dashboard/personal/alunos/$alunoId'
    | '/dashboard/personal/alunos'
  id:
    | '__root__'
    | '/'
    | '/dashboard/personal/agenda'
    | '/dashboard/personal/exercicios'
    | '/dashboard/personal/alunos/$alunoId'
    | '/dashboard/personal/alunos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardPersonalAgendaRoute: typeof DashboardPersonalAgendaRoute
  DashboardPersonalExerciciosRoute: typeof DashboardPersonalExerciciosRoute
  DashboardPersonalAlunosAlunoIdRoute: typeof DashboardPersonalAlunosAlunoIdRoute
  DashboardPersonalAlunosIndexRoute: typeof DashboardPersonalAlunosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/personal/exercicios': {
      id: '/dashboard/personal/exercicios'
      path: '/dashboard/personal/exercicios'
      fullPath: '/dashboard/personal/exercicios'
      preLoaderRoute: typeof DashboardPersonalExerciciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/personal/agenda': {
      id: '/dashboard/personal/agenda'
      path: '/dashboard/personal/agenda'
      fullPath: '/dashboard/personal/agenda'
      preLoaderRoute: typeof DashboardPersonalAgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/personal/alunos/': {
      id: '/dashboard/personal/alunos/'
      path: '/dashboard/personal/alunos'
      fullPath: '/dashboard/personal/alunos/'
      preLoaderRoute: typeof DashboardPersonalAlunosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/personal/alunos/$alunoId': {
      id: '/dashboard/personal/alunos/$alunoId'
      path: '/dashboard/personal/alunos/$alunoId'
      fullPath: '/dashboard/personal/alunos/$alunoId'
      preLoaderRoute: typeof DashboardPersonalAlunosAlunoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardPersonalAgendaRoute: DashboardPersonalAgendaRoute,
  DashboardPersonalExerciciosRoute: DashboardPersonalExerciciosRoute,
  DashboardPersonalAlunosAlunoIdRoute: DashboardPersonalAlunosAlunoIdRoute,
  DashboardPersonalAlunosIndexRoute: DashboardPersonalAlunosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
