/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedTreinosRouteImport } from './routes/_authenticated/treinos'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedMeuTreinoRouteImport } from './routes/_authenticated/meu-treino'
import { Route as AuthenticatedDesafiosRouteImport } from './routes/_authenticated/desafios'
import { Route as AuthenticatedAvaliacoesRouteImport } from './routes/_authenticated/avaliacoes'
import { Route as AuthenticatedPersonalRouteRouteImport } from './routes/_authenticated/_personal/route'
import { Route as AuthenticatedAlunoRouteRouteImport } from './routes/_authenticated/_aluno/route'
import { Route as AuthenticatedAcademiaRouteRouteImport } from './routes/_authenticated/_academia/route'
import { Route as AuthenticatedMeuTreinoTreinoIdRouteImport } from './routes/_authenticated/meu-treino.treino.$id'
import { Route as AuthenticatedAlunoDashboardAlunoIndexRouteImport } from './routes/_authenticated/_aluno/dashboard.aluno.index'
import { Route as AuthenticatedAcademiaDashboardAcademiaIndexRouteImport } from './routes/_authenticated/_academia/dashboard.academia.index'
import { Route as AuthenticatedPersonalDashboardPersonalFinanceiroRouteImport } from './routes/_authenticated/_personal/dashboard.personal.financeiro'
import { Route as AuthenticatedPersonalDashboardPersonalExerciciosRouteImport } from './routes/_authenticated/_personal/dashboard.personal.exercicios'
import { Route as AuthenticatedPersonalDashboardPersonalDesafiosRouteImport } from './routes/_authenticated/_personal/dashboard.personal.desafios'
import { Route as AuthenticatedPersonalDashboardPersonalAcademiaRouteImport } from './routes/_authenticated/_personal/dashboard.personal.academia'
import { Route as AuthenticatedAcademiaDashboardAcademiaFinanceiroRouteImport } from './routes/_authenticated/_academia/dashboard.academia.financeiro'
import { Route as AuthenticatedAcademiaDashboardAcademiaExerciciosRouteImport } from './routes/_authenticated/_academia/dashboard.academia.exercicios'
import { Route as AuthenticatedAcademiaDashboardAcademiaDesafiosRouteImport } from './routes/_authenticated/_academia/dashboard.academia.desafios'
import { Route as AuthenticatedAcademiaDashboardAcademiaConfiguracoesRouteImport } from './routes/_authenticated/_academia/dashboard.academia.configuracoes'
import { Route as AuthenticatedPersonalDashboardPersonalTreinosIndexRouteImport } from './routes/_authenticated/_personal/dashboard.personal.treinos.index'
import { Route as AuthenticatedPersonalDashboardPersonalPersonaisIndexRouteImport } from './routes/_authenticated/_personal/dashboard.personal.personais.index'
import { Route as AuthenticatedPersonalDashboardPersonalAvaliacoesIndexRouteImport } from './routes/_authenticated/_personal/dashboard.personal.avaliacoes.index'
import { Route as AuthenticatedPersonalDashboardPersonalAlunosIndexRouteImport } from './routes/_authenticated/_personal/dashboard.personal.alunos.index'
import { Route as AuthenticatedAcademiaDashboardAcademiaTreinosIndexRouteImport } from './routes/_authenticated/_academia/dashboard.academia.treinos.index'
import { Route as AuthenticatedAcademiaDashboardAcademiaPersonaisIndexRouteImport } from './routes/_authenticated/_academia/dashboard.academia.personais.index'
import { Route as AuthenticatedAcademiaDashboardAcademiaAvaliacoesIndexRouteImport } from './routes/_authenticated/_academia/dashboard.academia.avaliacoes.index'
import { Route as AuthenticatedAcademiaDashboardAcademiaAlunosIndexRouteImport } from './routes/_authenticated/_academia/dashboard.academia.alunos.index'
import { Route as AuthenticatedPersonalDashboardPersonalTreinosNovoTemplateRouteImport } from './routes/_authenticated/_personal/dashboard.personal.treinos.novo-template'
import { Route as AuthenticatedPersonalDashboardPersonalTreinosNovoPlanoRouteImport } from './routes/_authenticated/_personal/dashboard.personal.treinos.novo-plano'
import { Route as AuthenticatedPersonalDashboardPersonalPersonaisPersonalIdRouteImport } from './routes/_authenticated/_personal/dashboard.personal.personais.$personalId'
import { Route as AuthenticatedPersonalDashboardPersonalAvaliacoesAlunoIdRouteImport } from './routes/_authenticated/_personal/dashboard.personal.avaliacoes.$alunoId'
import { Route as AuthenticatedPersonalDashboardPersonalAvaliacaoAvaliacaoIdRouteImport } from './routes/_authenticated/_personal/dashboard.personal.avaliacao.$avaliacaoId'
import { Route as AuthenticatedPersonalDashboardPersonalAlunosAlunoIdRouteImport } from './routes/_authenticated/_personal/dashboard.personal.alunos.$alunoId'
import { Route as AuthenticatedAcademiaDashboardAcademiaTreinosNovoTemplateRouteImport } from './routes/_authenticated/_academia/dashboard.academia.treinos.novo-template'
import { Route as AuthenticatedAcademiaDashboardAcademiaTreinosNovoPlanoRouteImport } from './routes/_authenticated/_academia/dashboard.academia.treinos.novo-plano'
import { Route as AuthenticatedAcademiaDashboardAcademiaPersonaisPersonalIdRouteImport } from './routes/_authenticated/_academia/dashboard.academia.personais.$personalId'
import { Route as AuthenticatedAcademiaDashboardAcademiaAlunosAlunoIdRouteImport } from './routes/_authenticated/_academia/dashboard.academia.alunos.$alunoId'
import { Route as AuthenticatedPersonalDashboardPersonalTreinosPlanoPlanoIdRouteImport } from './routes/_authenticated/_personal/dashboard.personal.treinos.plano.$planoId'
import { Route as AuthenticatedPersonalDashboardPersonalTreinosModeloModeloIdRouteImport } from './routes/_authenticated/_personal/dashboard.personal.treinos.modelo.$modeloId'
import { Route as AuthenticatedPersonalDashboardPersonalTreinosEditarSlugRouteImport } from './routes/_authenticated/_personal/dashboard.personal.treinos.editar.$slug'
import { Route as AuthenticatedAcademiaDashboardAcademiaTreinosPlanoPlanoIdRouteImport } from './routes/_authenticated/_academia/dashboard.academia.treinos.plano.$planoId'
import { Route as AuthenticatedAcademiaDashboardAcademiaTreinosModeloModeloIdRouteImport } from './routes/_authenticated/_academia/dashboard.academia.treinos.modelo.$modeloId'
import { Route as AuthenticatedAcademiaDashboardAcademiaTreinosEditarSlugRouteImport } from './routes/_authenticated/_academia/dashboard.academia.treinos.editar.$slug'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTreinosRoute = AuthenticatedTreinosRouteImport.update({
  id: '/treinos',
  path: '/treinos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeuTreinoRoute = AuthenticatedMeuTreinoRouteImport.update({
  id: '/meu-treino',
  path: '/meu-treino',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDesafiosRoute = AuthenticatedDesafiosRouteImport.update({
  id: '/desafios',
  path: '/desafios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAvaliacoesRoute = AuthenticatedAvaliacoesRouteImport.update({
  id: '/avaliacoes',
  path: '/avaliacoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPersonalRouteRoute =
  AuthenticatedPersonalRouteRouteImport.update({
    id: '/_personal',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAlunoRouteRoute = AuthenticatedAlunoRouteRouteImport.update({
  id: '/_aluno',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAcademiaRouteRoute =
  AuthenticatedAcademiaRouteRouteImport.update({
    id: '/_academia',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMeuTreinoTreinoIdRoute =
  AuthenticatedMeuTreinoTreinoIdRouteImport.update({
    id: '/treino/$id',
    path: '/treino/$id',
    getParentRoute: () => AuthenticatedMeuTreinoRoute,
  } as any)
const AuthenticatedAlunoDashboardAlunoIndexRoute =
  AuthenticatedAlunoDashboardAlunoIndexRouteImport.update({
    id: '/dashboard/aluno/',
    path: '/dashboard/aluno/',
    getParentRoute: () => AuthenticatedAlunoRouteRoute,
  } as any)
const AuthenticatedAcademiaDashboardAcademiaIndexRoute =
  AuthenticatedAcademiaDashboardAcademiaIndexRouteImport.update({
    id: '/dashboard/academia/',
    path: '/dashboard/academia/',
    getParentRoute: () => AuthenticatedAcademiaRouteRoute,
  } as any)
const AuthenticatedPersonalDashboardPersonalFinanceiroRoute =
  AuthenticatedPersonalDashboardPersonalFinanceiroRouteImport.update({
    id: '/dashboard/personal/financeiro',
    path: '/dashboard/personal/financeiro',
    getParentRoute: () => AuthenticatedPersonalRouteRoute,
  } as any)
const AuthenticatedPersonalDashboardPersonalExerciciosRoute =
  AuthenticatedPersonalDashboardPersonalExerciciosRouteImport.update({
    id: '/dashboard/personal/exercicios',
    path: '/dashboard/personal/exercicios',
    getParentRoute: () => AuthenticatedPersonalRouteRoute,
  } as any)
const AuthenticatedPersonalDashboardPersonalDesafiosRoute =
  AuthenticatedPersonalDashboardPersonalDesafiosRouteImport.update({
    id: '/dashboard/personal/desafios',
    path: '/dashboard/personal/desafios',
    getParentRoute: () => AuthenticatedPersonalRouteRoute,
  } as any)
const AuthenticatedPersonalDashboardPersonalAcademiaRoute =
  AuthenticatedPersonalDashboardPersonalAcademiaRouteImport.update({
    id: '/dashboard/personal/academia',
    path: '/dashboard/personal/academia',
    getParentRoute: () => AuthenticatedPersonalRouteRoute,
  } as any)
const AuthenticatedAcademiaDashboardAcademiaFinanceiroRoute =
  AuthenticatedAcademiaDashboardAcademiaFinanceiroRouteImport.update({
    id: '/dashboard/academia/financeiro',
    path: '/dashboard/academia/financeiro',
    getParentRoute: () => AuthenticatedAcademiaRouteRoute,
  } as any)
const AuthenticatedAcademiaDashboardAcademiaExerciciosRoute =
  AuthenticatedAcademiaDashboardAcademiaExerciciosRouteImport.update({
    id: '/dashboard/academia/exercicios',
    path: '/dashboard/academia/exercicios',
    getParentRoute: () => AuthenticatedAcademiaRouteRoute,
  } as any)
const AuthenticatedAcademiaDashboardAcademiaDesafiosRoute =
  AuthenticatedAcademiaDashboardAcademiaDesafiosRouteImport.update({
    id: '/dashboard/academia/desafios',
    path: '/dashboard/academia/desafios',
    getParentRoute: () => AuthenticatedAcademiaRouteRoute,
  } as any)
const AuthenticatedAcademiaDashboardAcademiaConfiguracoesRoute =
  AuthenticatedAcademiaDashboardAcademiaConfiguracoesRouteImport.update({
    id: '/dashboard/academia/configuracoes',
    path: '/dashboard/academia/configuracoes',
    getParentRoute: () => AuthenticatedAcademiaRouteRoute,
  } as any)
const AuthenticatedPersonalDashboardPersonalTreinosIndexRoute =
  AuthenticatedPersonalDashboardPersonalTreinosIndexRouteImport.update({
    id: '/dashboard/personal/treinos/',
    path: '/dashboard/personal/treinos/',
    getParentRoute: () => AuthenticatedPersonalRouteRoute,
  } as any)
const AuthenticatedPersonalDashboardPersonalPersonaisIndexRoute =
  AuthenticatedPersonalDashboardPersonalPersonaisIndexRouteImport.update({
    id: '/dashboard/personal/personais/',
    path: '/dashboard/personal/personais/',
    getParentRoute: () => AuthenticatedPersonalRouteRoute,
  } as any)
const AuthenticatedPersonalDashboardPersonalAvaliacoesIndexRoute =
  AuthenticatedPersonalDashboardPersonalAvaliacoesIndexRouteImport.update({
    id: '/dashboard/personal/avaliacoes/',
    path: '/dashboard/personal/avaliacoes/',
    getParentRoute: () => AuthenticatedPersonalRouteRoute,
  } as any)
const AuthenticatedPersonalDashboardPersonalAlunosIndexRoute =
  AuthenticatedPersonalDashboardPersonalAlunosIndexRouteImport.update({
    id: '/dashboard/personal/alunos/',
    path: '/dashboard/personal/alunos/',
    getParentRoute: () => AuthenticatedPersonalRouteRoute,
  } as any)
const AuthenticatedAcademiaDashboardAcademiaTreinosIndexRoute =
  AuthenticatedAcademiaDashboardAcademiaTreinosIndexRouteImport.update({
    id: '/dashboard/academia/treinos/',
    path: '/dashboard/academia/treinos/',
    getParentRoute: () => AuthenticatedAcademiaRouteRoute,
  } as any)
const AuthenticatedAcademiaDashboardAcademiaPersonaisIndexRoute =
  AuthenticatedAcademiaDashboardAcademiaPersonaisIndexRouteImport.update({
    id: '/dashboard/academia/personais/',
    path: '/dashboard/academia/personais/',
    getParentRoute: () => AuthenticatedAcademiaRouteRoute,
  } as any)
const AuthenticatedAcademiaDashboardAcademiaAvaliacoesIndexRoute =
  AuthenticatedAcademiaDashboardAcademiaAvaliacoesIndexRouteImport.update({
    id: '/dashboard/academia/avaliacoes/',
    path: '/dashboard/academia/avaliacoes/',
    getParentRoute: () => AuthenticatedAcademiaRouteRoute,
  } as any)
const AuthenticatedAcademiaDashboardAcademiaAlunosIndexRoute =
  AuthenticatedAcademiaDashboardAcademiaAlunosIndexRouteImport.update({
    id: '/dashboard/academia/alunos/',
    path: '/dashboard/academia/alunos/',
    getParentRoute: () => AuthenticatedAcademiaRouteRoute,
  } as any)
const AuthenticatedPersonalDashboardPersonalTreinosNovoTemplateRoute =
  AuthenticatedPersonalDashboardPersonalTreinosNovoTemplateRouteImport.update({
    id: '/dashboard/personal/treinos/novo-template',
    path: '/dashboard/personal/treinos/novo-template',
    getParentRoute: () => AuthenticatedPersonalRouteRoute,
  } as any)
const AuthenticatedPersonalDashboardPersonalTreinosNovoPlanoRoute =
  AuthenticatedPersonalDashboardPersonalTreinosNovoPlanoRouteImport.update({
    id: '/dashboard/personal/treinos/novo-plano',
    path: '/dashboard/personal/treinos/novo-plano',
    getParentRoute: () => AuthenticatedPersonalRouteRoute,
  } as any)
const AuthenticatedPersonalDashboardPersonalPersonaisPersonalIdRoute =
  AuthenticatedPersonalDashboardPersonalPersonaisPersonalIdRouteImport.update({
    id: '/dashboard/personal/personais/$personalId',
    path: '/dashboard/personal/personais/$personalId',
    getParentRoute: () => AuthenticatedPersonalRouteRoute,
  } as any)
const AuthenticatedPersonalDashboardPersonalAvaliacoesAlunoIdRoute =
  AuthenticatedPersonalDashboardPersonalAvaliacoesAlunoIdRouteImport.update({
    id: '/dashboard/personal/avaliacoes/$alunoId',
    path: '/dashboard/personal/avaliacoes/$alunoId',
    getParentRoute: () => AuthenticatedPersonalRouteRoute,
  } as any)
const AuthenticatedPersonalDashboardPersonalAvaliacaoAvaliacaoIdRoute =
  AuthenticatedPersonalDashboardPersonalAvaliacaoAvaliacaoIdRouteImport.update({
    id: '/dashboard/personal/avaliacao/$avaliacaoId',
    path: '/dashboard/personal/avaliacao/$avaliacaoId',
    getParentRoute: () => AuthenticatedPersonalRouteRoute,
  } as any)
const AuthenticatedPersonalDashboardPersonalAlunosAlunoIdRoute =
  AuthenticatedPersonalDashboardPersonalAlunosAlunoIdRouteImport.update({
    id: '/dashboard/personal/alunos/$alunoId',
    path: '/dashboard/personal/alunos/$alunoId',
    getParentRoute: () => AuthenticatedPersonalRouteRoute,
  } as any)
const AuthenticatedAcademiaDashboardAcademiaTreinosNovoTemplateRoute =
  AuthenticatedAcademiaDashboardAcademiaTreinosNovoTemplateRouteImport.update({
    id: '/dashboard/academia/treinos/novo-template',
    path: '/dashboard/academia/treinos/novo-template',
    getParentRoute: () => AuthenticatedAcademiaRouteRoute,
  } as any)
const AuthenticatedAcademiaDashboardAcademiaTreinosNovoPlanoRoute =
  AuthenticatedAcademiaDashboardAcademiaTreinosNovoPlanoRouteImport.update({
    id: '/dashboard/academia/treinos/novo-plano',
    path: '/dashboard/academia/treinos/novo-plano',
    getParentRoute: () => AuthenticatedAcademiaRouteRoute,
  } as any)
const AuthenticatedAcademiaDashboardAcademiaPersonaisPersonalIdRoute =
  AuthenticatedAcademiaDashboardAcademiaPersonaisPersonalIdRouteImport.update({
    id: '/dashboard/academia/personais/$personalId',
    path: '/dashboard/academia/personais/$personalId',
    getParentRoute: () => AuthenticatedAcademiaRouteRoute,
  } as any)
const AuthenticatedAcademiaDashboardAcademiaAlunosAlunoIdRoute =
  AuthenticatedAcademiaDashboardAcademiaAlunosAlunoIdRouteImport.update({
    id: '/dashboard/academia/alunos/$alunoId',
    path: '/dashboard/academia/alunos/$alunoId',
    getParentRoute: () => AuthenticatedAcademiaRouteRoute,
  } as any)
const AuthenticatedPersonalDashboardPersonalTreinosPlanoPlanoIdRoute =
  AuthenticatedPersonalDashboardPersonalTreinosPlanoPlanoIdRouteImport.update({
    id: '/dashboard/personal/treinos/plano/$planoId',
    path: '/dashboard/personal/treinos/plano/$planoId',
    getParentRoute: () => AuthenticatedPersonalRouteRoute,
  } as any)
const AuthenticatedPersonalDashboardPersonalTreinosModeloModeloIdRoute =
  AuthenticatedPersonalDashboardPersonalTreinosModeloModeloIdRouteImport.update(
    {
      id: '/dashboard/personal/treinos/modelo/$modeloId',
      path: '/dashboard/personal/treinos/modelo/$modeloId',
      getParentRoute: () => AuthenticatedPersonalRouteRoute,
    } as any,
  )
const AuthenticatedPersonalDashboardPersonalTreinosEditarSlugRoute =
  AuthenticatedPersonalDashboardPersonalTreinosEditarSlugRouteImport.update({
    id: '/dashboard/personal/treinos/editar/$slug',
    path: '/dashboard/personal/treinos/editar/$slug',
    getParentRoute: () => AuthenticatedPersonalRouteRoute,
  } as any)
const AuthenticatedAcademiaDashboardAcademiaTreinosPlanoPlanoIdRoute =
  AuthenticatedAcademiaDashboardAcademiaTreinosPlanoPlanoIdRouteImport.update({
    id: '/dashboard/academia/treinos/plano/$planoId',
    path: '/dashboard/academia/treinos/plano/$planoId',
    getParentRoute: () => AuthenticatedAcademiaRouteRoute,
  } as any)
const AuthenticatedAcademiaDashboardAcademiaTreinosModeloModeloIdRoute =
  AuthenticatedAcademiaDashboardAcademiaTreinosModeloModeloIdRouteImport.update(
    {
      id: '/dashboard/academia/treinos/modelo/$modeloId',
      path: '/dashboard/academia/treinos/modelo/$modeloId',
      getParentRoute: () => AuthenticatedAcademiaRouteRoute,
    } as any,
  )
const AuthenticatedAcademiaDashboardAcademiaTreinosEditarSlugRoute =
  AuthenticatedAcademiaDashboardAcademiaTreinosEditarSlugRouteImport.update({
    id: '/dashboard/academia/treinos/editar/$slug',
    path: '/dashboard/academia/treinos/editar/$slug',
    getParentRoute: () => AuthenticatedAcademiaRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/avaliacoes': typeof AuthenticatedAvaliacoesRoute
  '/desafios': typeof AuthenticatedDesafiosRoute
  '/meu-treino': typeof AuthenticatedMeuTreinoRouteWithChildren
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/treinos': typeof AuthenticatedTreinosRoute
  '/meu-treino/treino/$id': typeof AuthenticatedMeuTreinoTreinoIdRoute
  '/dashboard/academia/configuracoes': typeof AuthenticatedAcademiaDashboardAcademiaConfiguracoesRoute
  '/dashboard/academia/desafios': typeof AuthenticatedAcademiaDashboardAcademiaDesafiosRoute
  '/dashboard/academia/exercicios': typeof AuthenticatedAcademiaDashboardAcademiaExerciciosRoute
  '/dashboard/academia/financeiro': typeof AuthenticatedAcademiaDashboardAcademiaFinanceiroRoute
  '/dashboard/personal/academia': typeof AuthenticatedPersonalDashboardPersonalAcademiaRoute
  '/dashboard/personal/desafios': typeof AuthenticatedPersonalDashboardPersonalDesafiosRoute
  '/dashboard/personal/exercicios': typeof AuthenticatedPersonalDashboardPersonalExerciciosRoute
  '/dashboard/personal/financeiro': typeof AuthenticatedPersonalDashboardPersonalFinanceiroRoute
  '/dashboard/academia/': typeof AuthenticatedAcademiaDashboardAcademiaIndexRoute
  '/dashboard/aluno/': typeof AuthenticatedAlunoDashboardAlunoIndexRoute
  '/dashboard/academia/alunos/$alunoId': typeof AuthenticatedAcademiaDashboardAcademiaAlunosAlunoIdRoute
  '/dashboard/academia/personais/$personalId': typeof AuthenticatedAcademiaDashboardAcademiaPersonaisPersonalIdRoute
  '/dashboard/academia/treinos/novo-plano': typeof AuthenticatedAcademiaDashboardAcademiaTreinosNovoPlanoRoute
  '/dashboard/academia/treinos/novo-template': typeof AuthenticatedAcademiaDashboardAcademiaTreinosNovoTemplateRoute
  '/dashboard/personal/alunos/$alunoId': typeof AuthenticatedPersonalDashboardPersonalAlunosAlunoIdRoute
  '/dashboard/personal/avaliacao/$avaliacaoId': typeof AuthenticatedPersonalDashboardPersonalAvaliacaoAvaliacaoIdRoute
  '/dashboard/personal/avaliacoes/$alunoId': typeof AuthenticatedPersonalDashboardPersonalAvaliacoesAlunoIdRoute
  '/dashboard/personal/personais/$personalId': typeof AuthenticatedPersonalDashboardPersonalPersonaisPersonalIdRoute
  '/dashboard/personal/treinos/novo-plano': typeof AuthenticatedPersonalDashboardPersonalTreinosNovoPlanoRoute
  '/dashboard/personal/treinos/novo-template': typeof AuthenticatedPersonalDashboardPersonalTreinosNovoTemplateRoute
  '/dashboard/academia/alunos/': typeof AuthenticatedAcademiaDashboardAcademiaAlunosIndexRoute
  '/dashboard/academia/avaliacoes/': typeof AuthenticatedAcademiaDashboardAcademiaAvaliacoesIndexRoute
  '/dashboard/academia/personais/': typeof AuthenticatedAcademiaDashboardAcademiaPersonaisIndexRoute
  '/dashboard/academia/treinos/': typeof AuthenticatedAcademiaDashboardAcademiaTreinosIndexRoute
  '/dashboard/personal/alunos/': typeof AuthenticatedPersonalDashboardPersonalAlunosIndexRoute
  '/dashboard/personal/avaliacoes/': typeof AuthenticatedPersonalDashboardPersonalAvaliacoesIndexRoute
  '/dashboard/personal/personais/': typeof AuthenticatedPersonalDashboardPersonalPersonaisIndexRoute
  '/dashboard/personal/treinos/': typeof AuthenticatedPersonalDashboardPersonalTreinosIndexRoute
  '/dashboard/academia/treinos/editar/$slug': typeof AuthenticatedAcademiaDashboardAcademiaTreinosEditarSlugRoute
  '/dashboard/academia/treinos/modelo/$modeloId': typeof AuthenticatedAcademiaDashboardAcademiaTreinosModeloModeloIdRoute
  '/dashboard/academia/treinos/plano/$planoId': typeof AuthenticatedAcademiaDashboardAcademiaTreinosPlanoPlanoIdRoute
  '/dashboard/personal/treinos/editar/$slug': typeof AuthenticatedPersonalDashboardPersonalTreinosEditarSlugRoute
  '/dashboard/personal/treinos/modelo/$modeloId': typeof AuthenticatedPersonalDashboardPersonalTreinosModeloModeloIdRoute
  '/dashboard/personal/treinos/plano/$planoId': typeof AuthenticatedPersonalDashboardPersonalTreinosPlanoPlanoIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/': typeof AuthenticatedIndexRoute
  '/avaliacoes': typeof AuthenticatedAvaliacoesRoute
  '/desafios': typeof AuthenticatedDesafiosRoute
  '/meu-treino': typeof AuthenticatedMeuTreinoRouteWithChildren
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/treinos': typeof AuthenticatedTreinosRoute
  '/meu-treino/treino/$id': typeof AuthenticatedMeuTreinoTreinoIdRoute
  '/dashboard/academia/configuracoes': typeof AuthenticatedAcademiaDashboardAcademiaConfiguracoesRoute
  '/dashboard/academia/desafios': typeof AuthenticatedAcademiaDashboardAcademiaDesafiosRoute
  '/dashboard/academia/exercicios': typeof AuthenticatedAcademiaDashboardAcademiaExerciciosRoute
  '/dashboard/academia/financeiro': typeof AuthenticatedAcademiaDashboardAcademiaFinanceiroRoute
  '/dashboard/personal/academia': typeof AuthenticatedPersonalDashboardPersonalAcademiaRoute
  '/dashboard/personal/desafios': typeof AuthenticatedPersonalDashboardPersonalDesafiosRoute
  '/dashboard/personal/exercicios': typeof AuthenticatedPersonalDashboardPersonalExerciciosRoute
  '/dashboard/personal/financeiro': typeof AuthenticatedPersonalDashboardPersonalFinanceiroRoute
  '/dashboard/academia': typeof AuthenticatedAcademiaDashboardAcademiaIndexRoute
  '/dashboard/aluno': typeof AuthenticatedAlunoDashboardAlunoIndexRoute
  '/dashboard/academia/alunos/$alunoId': typeof AuthenticatedAcademiaDashboardAcademiaAlunosAlunoIdRoute
  '/dashboard/academia/personais/$personalId': typeof AuthenticatedAcademiaDashboardAcademiaPersonaisPersonalIdRoute
  '/dashboard/academia/treinos/novo-plano': typeof AuthenticatedAcademiaDashboardAcademiaTreinosNovoPlanoRoute
  '/dashboard/academia/treinos/novo-template': typeof AuthenticatedAcademiaDashboardAcademiaTreinosNovoTemplateRoute
  '/dashboard/personal/alunos/$alunoId': typeof AuthenticatedPersonalDashboardPersonalAlunosAlunoIdRoute
  '/dashboard/personal/avaliacao/$avaliacaoId': typeof AuthenticatedPersonalDashboardPersonalAvaliacaoAvaliacaoIdRoute
  '/dashboard/personal/avaliacoes/$alunoId': typeof AuthenticatedPersonalDashboardPersonalAvaliacoesAlunoIdRoute
  '/dashboard/personal/personais/$personalId': typeof AuthenticatedPersonalDashboardPersonalPersonaisPersonalIdRoute
  '/dashboard/personal/treinos/novo-plano': typeof AuthenticatedPersonalDashboardPersonalTreinosNovoPlanoRoute
  '/dashboard/personal/treinos/novo-template': typeof AuthenticatedPersonalDashboardPersonalTreinosNovoTemplateRoute
  '/dashboard/academia/alunos': typeof AuthenticatedAcademiaDashboardAcademiaAlunosIndexRoute
  '/dashboard/academia/avaliacoes': typeof AuthenticatedAcademiaDashboardAcademiaAvaliacoesIndexRoute
  '/dashboard/academia/personais': typeof AuthenticatedAcademiaDashboardAcademiaPersonaisIndexRoute
  '/dashboard/academia/treinos': typeof AuthenticatedAcademiaDashboardAcademiaTreinosIndexRoute
  '/dashboard/personal/alunos': typeof AuthenticatedPersonalDashboardPersonalAlunosIndexRoute
  '/dashboard/personal/avaliacoes': typeof AuthenticatedPersonalDashboardPersonalAvaliacoesIndexRoute
  '/dashboard/personal/personais': typeof AuthenticatedPersonalDashboardPersonalPersonaisIndexRoute
  '/dashboard/personal/treinos': typeof AuthenticatedPersonalDashboardPersonalTreinosIndexRoute
  '/dashboard/academia/treinos/editar/$slug': typeof AuthenticatedAcademiaDashboardAcademiaTreinosEditarSlugRoute
  '/dashboard/academia/treinos/modelo/$modeloId': typeof AuthenticatedAcademiaDashboardAcademiaTreinosModeloModeloIdRoute
  '/dashboard/academia/treinos/plano/$planoId': typeof AuthenticatedAcademiaDashboardAcademiaTreinosPlanoPlanoIdRoute
  '/dashboard/personal/treinos/editar/$slug': typeof AuthenticatedPersonalDashboardPersonalTreinosEditarSlugRoute
  '/dashboard/personal/treinos/modelo/$modeloId': typeof AuthenticatedPersonalDashboardPersonalTreinosModeloModeloIdRoute
  '/dashboard/personal/treinos/plano/$planoId': typeof AuthenticatedPersonalDashboardPersonalTreinosPlanoPlanoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/_academia': typeof AuthenticatedAcademiaRouteRouteWithChildren
  '/_authenticated/_aluno': typeof AuthenticatedAlunoRouteRouteWithChildren
  '/_authenticated/_personal': typeof AuthenticatedPersonalRouteRouteWithChildren
  '/_authenticated/avaliacoes': typeof AuthenticatedAvaliacoesRoute
  '/_authenticated/desafios': typeof AuthenticatedDesafiosRoute
  '/_authenticated/meu-treino': typeof AuthenticatedMeuTreinoRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/treinos': typeof AuthenticatedTreinosRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/meu-treino/treino/$id': typeof AuthenticatedMeuTreinoTreinoIdRoute
  '/_authenticated/_academia/dashboard/academia/configuracoes': typeof AuthenticatedAcademiaDashboardAcademiaConfiguracoesRoute
  '/_authenticated/_academia/dashboard/academia/desafios': typeof AuthenticatedAcademiaDashboardAcademiaDesafiosRoute
  '/_authenticated/_academia/dashboard/academia/exercicios': typeof AuthenticatedAcademiaDashboardAcademiaExerciciosRoute
  '/_authenticated/_academia/dashboard/academia/financeiro': typeof AuthenticatedAcademiaDashboardAcademiaFinanceiroRoute
  '/_authenticated/_personal/dashboard/personal/academia': typeof AuthenticatedPersonalDashboardPersonalAcademiaRoute
  '/_authenticated/_personal/dashboard/personal/desafios': typeof AuthenticatedPersonalDashboardPersonalDesafiosRoute
  '/_authenticated/_personal/dashboard/personal/exercicios': typeof AuthenticatedPersonalDashboardPersonalExerciciosRoute
  '/_authenticated/_personal/dashboard/personal/financeiro': typeof AuthenticatedPersonalDashboardPersonalFinanceiroRoute
  '/_authenticated/_academia/dashboard/academia/': typeof AuthenticatedAcademiaDashboardAcademiaIndexRoute
  '/_authenticated/_aluno/dashboard/aluno/': typeof AuthenticatedAlunoDashboardAlunoIndexRoute
  '/_authenticated/_academia/dashboard/academia/alunos/$alunoId': typeof AuthenticatedAcademiaDashboardAcademiaAlunosAlunoIdRoute
  '/_authenticated/_academia/dashboard/academia/personais/$personalId': typeof AuthenticatedAcademiaDashboardAcademiaPersonaisPersonalIdRoute
  '/_authenticated/_academia/dashboard/academia/treinos/novo-plano': typeof AuthenticatedAcademiaDashboardAcademiaTreinosNovoPlanoRoute
  '/_authenticated/_academia/dashboard/academia/treinos/novo-template': typeof AuthenticatedAcademiaDashboardAcademiaTreinosNovoTemplateRoute
  '/_authenticated/_personal/dashboard/personal/alunos/$alunoId': typeof AuthenticatedPersonalDashboardPersonalAlunosAlunoIdRoute
  '/_authenticated/_personal/dashboard/personal/avaliacao/$avaliacaoId': typeof AuthenticatedPersonalDashboardPersonalAvaliacaoAvaliacaoIdRoute
  '/_authenticated/_personal/dashboard/personal/avaliacoes/$alunoId': typeof AuthenticatedPersonalDashboardPersonalAvaliacoesAlunoIdRoute
  '/_authenticated/_personal/dashboard/personal/personais/$personalId': typeof AuthenticatedPersonalDashboardPersonalPersonaisPersonalIdRoute
  '/_authenticated/_personal/dashboard/personal/treinos/novo-plano': typeof AuthenticatedPersonalDashboardPersonalTreinosNovoPlanoRoute
  '/_authenticated/_personal/dashboard/personal/treinos/novo-template': typeof AuthenticatedPersonalDashboardPersonalTreinosNovoTemplateRoute
  '/_authenticated/_academia/dashboard/academia/alunos/': typeof AuthenticatedAcademiaDashboardAcademiaAlunosIndexRoute
  '/_authenticated/_academia/dashboard/academia/avaliacoes/': typeof AuthenticatedAcademiaDashboardAcademiaAvaliacoesIndexRoute
  '/_authenticated/_academia/dashboard/academia/personais/': typeof AuthenticatedAcademiaDashboardAcademiaPersonaisIndexRoute
  '/_authenticated/_academia/dashboard/academia/treinos/': typeof AuthenticatedAcademiaDashboardAcademiaTreinosIndexRoute
  '/_authenticated/_personal/dashboard/personal/alunos/': typeof AuthenticatedPersonalDashboardPersonalAlunosIndexRoute
  '/_authenticated/_personal/dashboard/personal/avaliacoes/': typeof AuthenticatedPersonalDashboardPersonalAvaliacoesIndexRoute
  '/_authenticated/_personal/dashboard/personal/personais/': typeof AuthenticatedPersonalDashboardPersonalPersonaisIndexRoute
  '/_authenticated/_personal/dashboard/personal/treinos/': typeof AuthenticatedPersonalDashboardPersonalTreinosIndexRoute
  '/_authenticated/_academia/dashboard/academia/treinos/editar/$slug': typeof AuthenticatedAcademiaDashboardAcademiaTreinosEditarSlugRoute
  '/_authenticated/_academia/dashboard/academia/treinos/modelo/$modeloId': typeof AuthenticatedAcademiaDashboardAcademiaTreinosModeloModeloIdRoute
  '/_authenticated/_academia/dashboard/academia/treinos/plano/$planoId': typeof AuthenticatedAcademiaDashboardAcademiaTreinosPlanoPlanoIdRoute
  '/_authenticated/_personal/dashboard/personal/treinos/editar/$slug': typeof AuthenticatedPersonalDashboardPersonalTreinosEditarSlugRoute
  '/_authenticated/_personal/dashboard/personal/treinos/modelo/$modeloId': typeof AuthenticatedPersonalDashboardPersonalTreinosModeloModeloIdRoute
  '/_authenticated/_personal/dashboard/personal/treinos/plano/$planoId': typeof AuthenticatedPersonalDashboardPersonalTreinosPlanoPlanoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/reset-password'
    | '/avaliacoes'
    | '/desafios'
    | '/meu-treino'
    | '/onboarding'
    | '/perfil'
    | '/treinos'
    | '/meu-treino/treino/$id'
    | '/dashboard/academia/configuracoes'
    | '/dashboard/academia/desafios'
    | '/dashboard/academia/exercicios'
    | '/dashboard/academia/financeiro'
    | '/dashboard/personal/academia'
    | '/dashboard/personal/desafios'
    | '/dashboard/personal/exercicios'
    | '/dashboard/personal/financeiro'
    | '/dashboard/academia/'
    | '/dashboard/aluno/'
    | '/dashboard/academia/alunos/$alunoId'
    | '/dashboard/academia/personais/$personalId'
    | '/dashboard/academia/treinos/novo-plano'
    | '/dashboard/academia/treinos/novo-template'
    | '/dashboard/personal/alunos/$alunoId'
    | '/dashboard/personal/avaliacao/$avaliacaoId'
    | '/dashboard/personal/avaliacoes/$alunoId'
    | '/dashboard/personal/personais/$personalId'
    | '/dashboard/personal/treinos/novo-plano'
    | '/dashboard/personal/treinos/novo-template'
    | '/dashboard/academia/alunos/'
    | '/dashboard/academia/avaliacoes/'
    | '/dashboard/academia/personais/'
    | '/dashboard/academia/treinos/'
    | '/dashboard/personal/alunos/'
    | '/dashboard/personal/avaliacoes/'
    | '/dashboard/personal/personais/'
    | '/dashboard/personal/treinos/'
    | '/dashboard/academia/treinos/editar/$slug'
    | '/dashboard/academia/treinos/modelo/$modeloId'
    | '/dashboard/academia/treinos/plano/$planoId'
    | '/dashboard/personal/treinos/editar/$slug'
    | '/dashboard/personal/treinos/modelo/$modeloId'
    | '/dashboard/personal/treinos/plano/$planoId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/reset-password'
    | '/'
    | '/avaliacoes'
    | '/desafios'
    | '/meu-treino'
    | '/onboarding'
    | '/perfil'
    | '/treinos'
    | '/meu-treino/treino/$id'
    | '/dashboard/academia/configuracoes'
    | '/dashboard/academia/desafios'
    | '/dashboard/academia/exercicios'
    | '/dashboard/academia/financeiro'
    | '/dashboard/personal/academia'
    | '/dashboard/personal/desafios'
    | '/dashboard/personal/exercicios'
    | '/dashboard/personal/financeiro'
    | '/dashboard/academia'
    | '/dashboard/aluno'
    | '/dashboard/academia/alunos/$alunoId'
    | '/dashboard/academia/personais/$personalId'
    | '/dashboard/academia/treinos/novo-plano'
    | '/dashboard/academia/treinos/novo-template'
    | '/dashboard/personal/alunos/$alunoId'
    | '/dashboard/personal/avaliacao/$avaliacaoId'
    | '/dashboard/personal/avaliacoes/$alunoId'
    | '/dashboard/personal/personais/$personalId'
    | '/dashboard/personal/treinos/novo-plano'
    | '/dashboard/personal/treinos/novo-template'
    | '/dashboard/academia/alunos'
    | '/dashboard/academia/avaliacoes'
    | '/dashboard/academia/personais'
    | '/dashboard/academia/treinos'
    | '/dashboard/personal/alunos'
    | '/dashboard/personal/avaliacoes'
    | '/dashboard/personal/personais'
    | '/dashboard/personal/treinos'
    | '/dashboard/academia/treinos/editar/$slug'
    | '/dashboard/academia/treinos/modelo/$modeloId'
    | '/dashboard/academia/treinos/plano/$planoId'
    | '/dashboard/personal/treinos/editar/$slug'
    | '/dashboard/personal/treinos/modelo/$modeloId'
    | '/dashboard/personal/treinos/plano/$planoId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/reset-password'
    | '/_authenticated/_academia'
    | '/_authenticated/_aluno'
    | '/_authenticated/_personal'
    | '/_authenticated/avaliacoes'
    | '/_authenticated/desafios'
    | '/_authenticated/meu-treino'
    | '/_authenticated/onboarding'
    | '/_authenticated/perfil'
    | '/_authenticated/treinos'
    | '/_authenticated/'
    | '/_authenticated/meu-treino/treino/$id'
    | '/_authenticated/_academia/dashboard/academia/configuracoes'
    | '/_authenticated/_academia/dashboard/academia/desafios'
    | '/_authenticated/_academia/dashboard/academia/exercicios'
    | '/_authenticated/_academia/dashboard/academia/financeiro'
    | '/_authenticated/_personal/dashboard/personal/academia'
    | '/_authenticated/_personal/dashboard/personal/desafios'
    | '/_authenticated/_personal/dashboard/personal/exercicios'
    | '/_authenticated/_personal/dashboard/personal/financeiro'
    | '/_authenticated/_academia/dashboard/academia/'
    | '/_authenticated/_aluno/dashboard/aluno/'
    | '/_authenticated/_academia/dashboard/academia/alunos/$alunoId'
    | '/_authenticated/_academia/dashboard/academia/personais/$personalId'
    | '/_authenticated/_academia/dashboard/academia/treinos/novo-plano'
    | '/_authenticated/_academia/dashboard/academia/treinos/novo-template'
    | '/_authenticated/_personal/dashboard/personal/alunos/$alunoId'
    | '/_authenticated/_personal/dashboard/personal/avaliacao/$avaliacaoId'
    | '/_authenticated/_personal/dashboard/personal/avaliacoes/$alunoId'
    | '/_authenticated/_personal/dashboard/personal/personais/$personalId'
    | '/_authenticated/_personal/dashboard/personal/treinos/novo-plano'
    | '/_authenticated/_personal/dashboard/personal/treinos/novo-template'
    | '/_authenticated/_academia/dashboard/academia/alunos/'
    | '/_authenticated/_academia/dashboard/academia/avaliacoes/'
    | '/_authenticated/_academia/dashboard/academia/personais/'
    | '/_authenticated/_academia/dashboard/academia/treinos/'
    | '/_authenticated/_personal/dashboard/personal/alunos/'
    | '/_authenticated/_personal/dashboard/personal/avaliacoes/'
    | '/_authenticated/_personal/dashboard/personal/personais/'
    | '/_authenticated/_personal/dashboard/personal/treinos/'
    | '/_authenticated/_academia/dashboard/academia/treinos/editar/$slug'
    | '/_authenticated/_academia/dashboard/academia/treinos/modelo/$modeloId'
    | '/_authenticated/_academia/dashboard/academia/treinos/plano/$planoId'
    | '/_authenticated/_personal/dashboard/personal/treinos/editar/$slug'
    | '/_authenticated/_personal/dashboard/personal/treinos/modelo/$modeloId'
    | '/_authenticated/_personal/dashboard/personal/treinos/plano/$planoId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/treinos': {
      id: '/_authenticated/treinos'
      path: '/treinos'
      fullPath: '/treinos'
      preLoaderRoute: typeof AuthenticatedTreinosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meu-treino': {
      id: '/_authenticated/meu-treino'
      path: '/meu-treino'
      fullPath: '/meu-treino'
      preLoaderRoute: typeof AuthenticatedMeuTreinoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/desafios': {
      id: '/_authenticated/desafios'
      path: '/desafios'
      fullPath: '/desafios'
      preLoaderRoute: typeof AuthenticatedDesafiosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/avaliacoes': {
      id: '/_authenticated/avaliacoes'
      path: '/avaliacoes'
      fullPath: '/avaliacoes'
      preLoaderRoute: typeof AuthenticatedAvaliacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_personal': {
      id: '/_authenticated/_personal'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedPersonalRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_aluno': {
      id: '/_authenticated/_aluno'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAlunoRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_academia': {
      id: '/_authenticated/_academia'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAcademiaRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meu-treino/treino/$id': {
      id: '/_authenticated/meu-treino/treino/$id'
      path: '/treino/$id'
      fullPath: '/meu-treino/treino/$id'
      preLoaderRoute: typeof AuthenticatedMeuTreinoTreinoIdRouteImport
      parentRoute: typeof AuthenticatedMeuTreinoRoute
    }
    '/_authenticated/_aluno/dashboard/aluno/': {
      id: '/_authenticated/_aluno/dashboard/aluno/'
      path: '/dashboard/aluno'
      fullPath: '/dashboard/aluno/'
      preLoaderRoute: typeof AuthenticatedAlunoDashboardAlunoIndexRouteImport
      parentRoute: typeof AuthenticatedAlunoRouteRoute
    }
    '/_authenticated/_academia/dashboard/academia/': {
      id: '/_authenticated/_academia/dashboard/academia/'
      path: '/dashboard/academia'
      fullPath: '/dashboard/academia/'
      preLoaderRoute: typeof AuthenticatedAcademiaDashboardAcademiaIndexRouteImport
      parentRoute: typeof AuthenticatedAcademiaRouteRoute
    }
    '/_authenticated/_personal/dashboard/personal/financeiro': {
      id: '/_authenticated/_personal/dashboard/personal/financeiro'
      path: '/dashboard/personal/financeiro'
      fullPath: '/dashboard/personal/financeiro'
      preLoaderRoute: typeof AuthenticatedPersonalDashboardPersonalFinanceiroRouteImport
      parentRoute: typeof AuthenticatedPersonalRouteRoute
    }
    '/_authenticated/_personal/dashboard/personal/exercicios': {
      id: '/_authenticated/_personal/dashboard/personal/exercicios'
      path: '/dashboard/personal/exercicios'
      fullPath: '/dashboard/personal/exercicios'
      preLoaderRoute: typeof AuthenticatedPersonalDashboardPersonalExerciciosRouteImport
      parentRoute: typeof AuthenticatedPersonalRouteRoute
    }
    '/_authenticated/_personal/dashboard/personal/desafios': {
      id: '/_authenticated/_personal/dashboard/personal/desafios'
      path: '/dashboard/personal/desafios'
      fullPath: '/dashboard/personal/desafios'
      preLoaderRoute: typeof AuthenticatedPersonalDashboardPersonalDesafiosRouteImport
      parentRoute: typeof AuthenticatedPersonalRouteRoute
    }
    '/_authenticated/_personal/dashboard/personal/academia': {
      id: '/_authenticated/_personal/dashboard/personal/academia'
      path: '/dashboard/personal/academia'
      fullPath: '/dashboard/personal/academia'
      preLoaderRoute: typeof AuthenticatedPersonalDashboardPersonalAcademiaRouteImport
      parentRoute: typeof AuthenticatedPersonalRouteRoute
    }
    '/_authenticated/_academia/dashboard/academia/financeiro': {
      id: '/_authenticated/_academia/dashboard/academia/financeiro'
      path: '/dashboard/academia/financeiro'
      fullPath: '/dashboard/academia/financeiro'
      preLoaderRoute: typeof AuthenticatedAcademiaDashboardAcademiaFinanceiroRouteImport
      parentRoute: typeof AuthenticatedAcademiaRouteRoute
    }
    '/_authenticated/_academia/dashboard/academia/exercicios': {
      id: '/_authenticated/_academia/dashboard/academia/exercicios'
      path: '/dashboard/academia/exercicios'
      fullPath: '/dashboard/academia/exercicios'
      preLoaderRoute: typeof AuthenticatedAcademiaDashboardAcademiaExerciciosRouteImport
      parentRoute: typeof AuthenticatedAcademiaRouteRoute
    }
    '/_authenticated/_academia/dashboard/academia/desafios': {
      id: '/_authenticated/_academia/dashboard/academia/desafios'
      path: '/dashboard/academia/desafios'
      fullPath: '/dashboard/academia/desafios'
      preLoaderRoute: typeof AuthenticatedAcademiaDashboardAcademiaDesafiosRouteImport
      parentRoute: typeof AuthenticatedAcademiaRouteRoute
    }
    '/_authenticated/_academia/dashboard/academia/configuracoes': {
      id: '/_authenticated/_academia/dashboard/academia/configuracoes'
      path: '/dashboard/academia/configuracoes'
      fullPath: '/dashboard/academia/configuracoes'
      preLoaderRoute: typeof AuthenticatedAcademiaDashboardAcademiaConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedAcademiaRouteRoute
    }
    '/_authenticated/_personal/dashboard/personal/treinos/': {
      id: '/_authenticated/_personal/dashboard/personal/treinos/'
      path: '/dashboard/personal/treinos'
      fullPath: '/dashboard/personal/treinos/'
      preLoaderRoute: typeof AuthenticatedPersonalDashboardPersonalTreinosIndexRouteImport
      parentRoute: typeof AuthenticatedPersonalRouteRoute
    }
    '/_authenticated/_personal/dashboard/personal/personais/': {
      id: '/_authenticated/_personal/dashboard/personal/personais/'
      path: '/dashboard/personal/personais'
      fullPath: '/dashboard/personal/personais/'
      preLoaderRoute: typeof AuthenticatedPersonalDashboardPersonalPersonaisIndexRouteImport
      parentRoute: typeof AuthenticatedPersonalRouteRoute
    }
    '/_authenticated/_personal/dashboard/personal/avaliacoes/': {
      id: '/_authenticated/_personal/dashboard/personal/avaliacoes/'
      path: '/dashboard/personal/avaliacoes'
      fullPath: '/dashboard/personal/avaliacoes/'
      preLoaderRoute: typeof AuthenticatedPersonalDashboardPersonalAvaliacoesIndexRouteImport
      parentRoute: typeof AuthenticatedPersonalRouteRoute
    }
    '/_authenticated/_personal/dashboard/personal/alunos/': {
      id: '/_authenticated/_personal/dashboard/personal/alunos/'
      path: '/dashboard/personal/alunos'
      fullPath: '/dashboard/personal/alunos/'
      preLoaderRoute: typeof AuthenticatedPersonalDashboardPersonalAlunosIndexRouteImport
      parentRoute: typeof AuthenticatedPersonalRouteRoute
    }
    '/_authenticated/_academia/dashboard/academia/treinos/': {
      id: '/_authenticated/_academia/dashboard/academia/treinos/'
      path: '/dashboard/academia/treinos'
      fullPath: '/dashboard/academia/treinos/'
      preLoaderRoute: typeof AuthenticatedAcademiaDashboardAcademiaTreinosIndexRouteImport
      parentRoute: typeof AuthenticatedAcademiaRouteRoute
    }
    '/_authenticated/_academia/dashboard/academia/personais/': {
      id: '/_authenticated/_academia/dashboard/academia/personais/'
      path: '/dashboard/academia/personais'
      fullPath: '/dashboard/academia/personais/'
      preLoaderRoute: typeof AuthenticatedAcademiaDashboardAcademiaPersonaisIndexRouteImport
      parentRoute: typeof AuthenticatedAcademiaRouteRoute
    }
    '/_authenticated/_academia/dashboard/academia/avaliacoes/': {
      id: '/_authenticated/_academia/dashboard/academia/avaliacoes/'
      path: '/dashboard/academia/avaliacoes'
      fullPath: '/dashboard/academia/avaliacoes/'
      preLoaderRoute: typeof AuthenticatedAcademiaDashboardAcademiaAvaliacoesIndexRouteImport
      parentRoute: typeof AuthenticatedAcademiaRouteRoute
    }
    '/_authenticated/_academia/dashboard/academia/alunos/': {
      id: '/_authenticated/_academia/dashboard/academia/alunos/'
      path: '/dashboard/academia/alunos'
      fullPath: '/dashboard/academia/alunos/'
      preLoaderRoute: typeof AuthenticatedAcademiaDashboardAcademiaAlunosIndexRouteImport
      parentRoute: typeof AuthenticatedAcademiaRouteRoute
    }
    '/_authenticated/_personal/dashboard/personal/treinos/novo-template': {
      id: '/_authenticated/_personal/dashboard/personal/treinos/novo-template'
      path: '/dashboard/personal/treinos/novo-template'
      fullPath: '/dashboard/personal/treinos/novo-template'
      preLoaderRoute: typeof AuthenticatedPersonalDashboardPersonalTreinosNovoTemplateRouteImport
      parentRoute: typeof AuthenticatedPersonalRouteRoute
    }
    '/_authenticated/_personal/dashboard/personal/treinos/novo-plano': {
      id: '/_authenticated/_personal/dashboard/personal/treinos/novo-plano'
      path: '/dashboard/personal/treinos/novo-plano'
      fullPath: '/dashboard/personal/treinos/novo-plano'
      preLoaderRoute: typeof AuthenticatedPersonalDashboardPersonalTreinosNovoPlanoRouteImport
      parentRoute: typeof AuthenticatedPersonalRouteRoute
    }
    '/_authenticated/_personal/dashboard/personal/personais/$personalId': {
      id: '/_authenticated/_personal/dashboard/personal/personais/$personalId'
      path: '/dashboard/personal/personais/$personalId'
      fullPath: '/dashboard/personal/personais/$personalId'
      preLoaderRoute: typeof AuthenticatedPersonalDashboardPersonalPersonaisPersonalIdRouteImport
      parentRoute: typeof AuthenticatedPersonalRouteRoute
    }
    '/_authenticated/_personal/dashboard/personal/avaliacoes/$alunoId': {
      id: '/_authenticated/_personal/dashboard/personal/avaliacoes/$alunoId'
      path: '/dashboard/personal/avaliacoes/$alunoId'
      fullPath: '/dashboard/personal/avaliacoes/$alunoId'
      preLoaderRoute: typeof AuthenticatedPersonalDashboardPersonalAvaliacoesAlunoIdRouteImport
      parentRoute: typeof AuthenticatedPersonalRouteRoute
    }
    '/_authenticated/_personal/dashboard/personal/avaliacao/$avaliacaoId': {
      id: '/_authenticated/_personal/dashboard/personal/avaliacao/$avaliacaoId'
      path: '/dashboard/personal/avaliacao/$avaliacaoId'
      fullPath: '/dashboard/personal/avaliacao/$avaliacaoId'
      preLoaderRoute: typeof AuthenticatedPersonalDashboardPersonalAvaliacaoAvaliacaoIdRouteImport
      parentRoute: typeof AuthenticatedPersonalRouteRoute
    }
    '/_authenticated/_personal/dashboard/personal/alunos/$alunoId': {
      id: '/_authenticated/_personal/dashboard/personal/alunos/$alunoId'
      path: '/dashboard/personal/alunos/$alunoId'
      fullPath: '/dashboard/personal/alunos/$alunoId'
      preLoaderRoute: typeof AuthenticatedPersonalDashboardPersonalAlunosAlunoIdRouteImport
      parentRoute: typeof AuthenticatedPersonalRouteRoute
    }
    '/_authenticated/_academia/dashboard/academia/treinos/novo-template': {
      id: '/_authenticated/_academia/dashboard/academia/treinos/novo-template'
      path: '/dashboard/academia/treinos/novo-template'
      fullPath: '/dashboard/academia/treinos/novo-template'
      preLoaderRoute: typeof AuthenticatedAcademiaDashboardAcademiaTreinosNovoTemplateRouteImport
      parentRoute: typeof AuthenticatedAcademiaRouteRoute
    }
    '/_authenticated/_academia/dashboard/academia/treinos/novo-plano': {
      id: '/_authenticated/_academia/dashboard/academia/treinos/novo-plano'
      path: '/dashboard/academia/treinos/novo-plano'
      fullPath: '/dashboard/academia/treinos/novo-plano'
      preLoaderRoute: typeof AuthenticatedAcademiaDashboardAcademiaTreinosNovoPlanoRouteImport
      parentRoute: typeof AuthenticatedAcademiaRouteRoute
    }
    '/_authenticated/_academia/dashboard/academia/personais/$personalId': {
      id: '/_authenticated/_academia/dashboard/academia/personais/$personalId'
      path: '/dashboard/academia/personais/$personalId'
      fullPath: '/dashboard/academia/personais/$personalId'
      preLoaderRoute: typeof AuthenticatedAcademiaDashboardAcademiaPersonaisPersonalIdRouteImport
      parentRoute: typeof AuthenticatedAcademiaRouteRoute
    }
    '/_authenticated/_academia/dashboard/academia/alunos/$alunoId': {
      id: '/_authenticated/_academia/dashboard/academia/alunos/$alunoId'
      path: '/dashboard/academia/alunos/$alunoId'
      fullPath: '/dashboard/academia/alunos/$alunoId'
      preLoaderRoute: typeof AuthenticatedAcademiaDashboardAcademiaAlunosAlunoIdRouteImport
      parentRoute: typeof AuthenticatedAcademiaRouteRoute
    }
    '/_authenticated/_personal/dashboard/personal/treinos/plano/$planoId': {
      id: '/_authenticated/_personal/dashboard/personal/treinos/plano/$planoId'
      path: '/dashboard/personal/treinos/plano/$planoId'
      fullPath: '/dashboard/personal/treinos/plano/$planoId'
      preLoaderRoute: typeof AuthenticatedPersonalDashboardPersonalTreinosPlanoPlanoIdRouteImport
      parentRoute: typeof AuthenticatedPersonalRouteRoute
    }
    '/_authenticated/_personal/dashboard/personal/treinos/modelo/$modeloId': {
      id: '/_authenticated/_personal/dashboard/personal/treinos/modelo/$modeloId'
      path: '/dashboard/personal/treinos/modelo/$modeloId'
      fullPath: '/dashboard/personal/treinos/modelo/$modeloId'
      preLoaderRoute: typeof AuthenticatedPersonalDashboardPersonalTreinosModeloModeloIdRouteImport
      parentRoute: typeof AuthenticatedPersonalRouteRoute
    }
    '/_authenticated/_personal/dashboard/personal/treinos/editar/$slug': {
      id: '/_authenticated/_personal/dashboard/personal/treinos/editar/$slug'
      path: '/dashboard/personal/treinos/editar/$slug'
      fullPath: '/dashboard/personal/treinos/editar/$slug'
      preLoaderRoute: typeof AuthenticatedPersonalDashboardPersonalTreinosEditarSlugRouteImport
      parentRoute: typeof AuthenticatedPersonalRouteRoute
    }
    '/_authenticated/_academia/dashboard/academia/treinos/plano/$planoId': {
      id: '/_authenticated/_academia/dashboard/academia/treinos/plano/$planoId'
      path: '/dashboard/academia/treinos/plano/$planoId'
      fullPath: '/dashboard/academia/treinos/plano/$planoId'
      preLoaderRoute: typeof AuthenticatedAcademiaDashboardAcademiaTreinosPlanoPlanoIdRouteImport
      parentRoute: typeof AuthenticatedAcademiaRouteRoute
    }
    '/_authenticated/_academia/dashboard/academia/treinos/modelo/$modeloId': {
      id: '/_authenticated/_academia/dashboard/academia/treinos/modelo/$modeloId'
      path: '/dashboard/academia/treinos/modelo/$modeloId'
      fullPath: '/dashboard/academia/treinos/modelo/$modeloId'
      preLoaderRoute: typeof AuthenticatedAcademiaDashboardAcademiaTreinosModeloModeloIdRouteImport
      parentRoute: typeof AuthenticatedAcademiaRouteRoute
    }
    '/_authenticated/_academia/dashboard/academia/treinos/editar/$slug': {
      id: '/_authenticated/_academia/dashboard/academia/treinos/editar/$slug'
      path: '/dashboard/academia/treinos/editar/$slug'
      fullPath: '/dashboard/academia/treinos/editar/$slug'
      preLoaderRoute: typeof AuthenticatedAcademiaDashboardAcademiaTreinosEditarSlugRouteImport
      parentRoute: typeof AuthenticatedAcademiaRouteRoute
    }
  }
}

interface AuthenticatedAcademiaRouteRouteChildren {
  AuthenticatedAcademiaDashboardAcademiaConfiguracoesRoute: typeof AuthenticatedAcademiaDashboardAcademiaConfiguracoesRoute
  AuthenticatedAcademiaDashboardAcademiaDesafiosRoute: typeof AuthenticatedAcademiaDashboardAcademiaDesafiosRoute
  AuthenticatedAcademiaDashboardAcademiaExerciciosRoute: typeof AuthenticatedAcademiaDashboardAcademiaExerciciosRoute
  AuthenticatedAcademiaDashboardAcademiaFinanceiroRoute: typeof AuthenticatedAcademiaDashboardAcademiaFinanceiroRoute
  AuthenticatedAcademiaDashboardAcademiaIndexRoute: typeof AuthenticatedAcademiaDashboardAcademiaIndexRoute
  AuthenticatedAcademiaDashboardAcademiaAlunosAlunoIdRoute: typeof AuthenticatedAcademiaDashboardAcademiaAlunosAlunoIdRoute
  AuthenticatedAcademiaDashboardAcademiaPersonaisPersonalIdRoute: typeof AuthenticatedAcademiaDashboardAcademiaPersonaisPersonalIdRoute
  AuthenticatedAcademiaDashboardAcademiaTreinosNovoPlanoRoute: typeof AuthenticatedAcademiaDashboardAcademiaTreinosNovoPlanoRoute
  AuthenticatedAcademiaDashboardAcademiaTreinosNovoTemplateRoute: typeof AuthenticatedAcademiaDashboardAcademiaTreinosNovoTemplateRoute
  AuthenticatedAcademiaDashboardAcademiaAlunosIndexRoute: typeof AuthenticatedAcademiaDashboardAcademiaAlunosIndexRoute
  AuthenticatedAcademiaDashboardAcademiaAvaliacoesIndexRoute: typeof AuthenticatedAcademiaDashboardAcademiaAvaliacoesIndexRoute
  AuthenticatedAcademiaDashboardAcademiaPersonaisIndexRoute: typeof AuthenticatedAcademiaDashboardAcademiaPersonaisIndexRoute
  AuthenticatedAcademiaDashboardAcademiaTreinosIndexRoute: typeof AuthenticatedAcademiaDashboardAcademiaTreinosIndexRoute
  AuthenticatedAcademiaDashboardAcademiaTreinosEditarSlugRoute: typeof AuthenticatedAcademiaDashboardAcademiaTreinosEditarSlugRoute
  AuthenticatedAcademiaDashboardAcademiaTreinosModeloModeloIdRoute: typeof AuthenticatedAcademiaDashboardAcademiaTreinosModeloModeloIdRoute
  AuthenticatedAcademiaDashboardAcademiaTreinosPlanoPlanoIdRoute: typeof AuthenticatedAcademiaDashboardAcademiaTreinosPlanoPlanoIdRoute
}

const AuthenticatedAcademiaRouteRouteChildren: AuthenticatedAcademiaRouteRouteChildren =
  {
    AuthenticatedAcademiaDashboardAcademiaConfiguracoesRoute:
      AuthenticatedAcademiaDashboardAcademiaConfiguracoesRoute,
    AuthenticatedAcademiaDashboardAcademiaDesafiosRoute:
      AuthenticatedAcademiaDashboardAcademiaDesafiosRoute,
    AuthenticatedAcademiaDashboardAcademiaExerciciosRoute:
      AuthenticatedAcademiaDashboardAcademiaExerciciosRoute,
    AuthenticatedAcademiaDashboardAcademiaFinanceiroRoute:
      AuthenticatedAcademiaDashboardAcademiaFinanceiroRoute,
    AuthenticatedAcademiaDashboardAcademiaIndexRoute:
      AuthenticatedAcademiaDashboardAcademiaIndexRoute,
    AuthenticatedAcademiaDashboardAcademiaAlunosAlunoIdRoute:
      AuthenticatedAcademiaDashboardAcademiaAlunosAlunoIdRoute,
    AuthenticatedAcademiaDashboardAcademiaPersonaisPersonalIdRoute:
      AuthenticatedAcademiaDashboardAcademiaPersonaisPersonalIdRoute,
    AuthenticatedAcademiaDashboardAcademiaTreinosNovoPlanoRoute:
      AuthenticatedAcademiaDashboardAcademiaTreinosNovoPlanoRoute,
    AuthenticatedAcademiaDashboardAcademiaTreinosNovoTemplateRoute:
      AuthenticatedAcademiaDashboardAcademiaTreinosNovoTemplateRoute,
    AuthenticatedAcademiaDashboardAcademiaAlunosIndexRoute:
      AuthenticatedAcademiaDashboardAcademiaAlunosIndexRoute,
    AuthenticatedAcademiaDashboardAcademiaAvaliacoesIndexRoute:
      AuthenticatedAcademiaDashboardAcademiaAvaliacoesIndexRoute,
    AuthenticatedAcademiaDashboardAcademiaPersonaisIndexRoute:
      AuthenticatedAcademiaDashboardAcademiaPersonaisIndexRoute,
    AuthenticatedAcademiaDashboardAcademiaTreinosIndexRoute:
      AuthenticatedAcademiaDashboardAcademiaTreinosIndexRoute,
    AuthenticatedAcademiaDashboardAcademiaTreinosEditarSlugRoute:
      AuthenticatedAcademiaDashboardAcademiaTreinosEditarSlugRoute,
    AuthenticatedAcademiaDashboardAcademiaTreinosModeloModeloIdRoute:
      AuthenticatedAcademiaDashboardAcademiaTreinosModeloModeloIdRoute,
    AuthenticatedAcademiaDashboardAcademiaTreinosPlanoPlanoIdRoute:
      AuthenticatedAcademiaDashboardAcademiaTreinosPlanoPlanoIdRoute,
  }

const AuthenticatedAcademiaRouteRouteWithChildren =
  AuthenticatedAcademiaRouteRoute._addFileChildren(
    AuthenticatedAcademiaRouteRouteChildren,
  )

interface AuthenticatedAlunoRouteRouteChildren {
  AuthenticatedAlunoDashboardAlunoIndexRoute: typeof AuthenticatedAlunoDashboardAlunoIndexRoute
}

const AuthenticatedAlunoRouteRouteChildren: AuthenticatedAlunoRouteRouteChildren =
  {
    AuthenticatedAlunoDashboardAlunoIndexRoute:
      AuthenticatedAlunoDashboardAlunoIndexRoute,
  }

const AuthenticatedAlunoRouteRouteWithChildren =
  AuthenticatedAlunoRouteRoute._addFileChildren(
    AuthenticatedAlunoRouteRouteChildren,
  )

interface AuthenticatedPersonalRouteRouteChildren {
  AuthenticatedPersonalDashboardPersonalAcademiaRoute: typeof AuthenticatedPersonalDashboardPersonalAcademiaRoute
  AuthenticatedPersonalDashboardPersonalDesafiosRoute: typeof AuthenticatedPersonalDashboardPersonalDesafiosRoute
  AuthenticatedPersonalDashboardPersonalExerciciosRoute: typeof AuthenticatedPersonalDashboardPersonalExerciciosRoute
  AuthenticatedPersonalDashboardPersonalFinanceiroRoute: typeof AuthenticatedPersonalDashboardPersonalFinanceiroRoute
  AuthenticatedPersonalDashboardPersonalAlunosAlunoIdRoute: typeof AuthenticatedPersonalDashboardPersonalAlunosAlunoIdRoute
  AuthenticatedPersonalDashboardPersonalAvaliacaoAvaliacaoIdRoute: typeof AuthenticatedPersonalDashboardPersonalAvaliacaoAvaliacaoIdRoute
  AuthenticatedPersonalDashboardPersonalAvaliacoesAlunoIdRoute: typeof AuthenticatedPersonalDashboardPersonalAvaliacoesAlunoIdRoute
  AuthenticatedPersonalDashboardPersonalPersonaisPersonalIdRoute: typeof AuthenticatedPersonalDashboardPersonalPersonaisPersonalIdRoute
  AuthenticatedPersonalDashboardPersonalTreinosNovoPlanoRoute: typeof AuthenticatedPersonalDashboardPersonalTreinosNovoPlanoRoute
  AuthenticatedPersonalDashboardPersonalTreinosNovoTemplateRoute: typeof AuthenticatedPersonalDashboardPersonalTreinosNovoTemplateRoute
  AuthenticatedPersonalDashboardPersonalAlunosIndexRoute: typeof AuthenticatedPersonalDashboardPersonalAlunosIndexRoute
  AuthenticatedPersonalDashboardPersonalAvaliacoesIndexRoute: typeof AuthenticatedPersonalDashboardPersonalAvaliacoesIndexRoute
  AuthenticatedPersonalDashboardPersonalPersonaisIndexRoute: typeof AuthenticatedPersonalDashboardPersonalPersonaisIndexRoute
  AuthenticatedPersonalDashboardPersonalTreinosIndexRoute: typeof AuthenticatedPersonalDashboardPersonalTreinosIndexRoute
  AuthenticatedPersonalDashboardPersonalTreinosEditarSlugRoute: typeof AuthenticatedPersonalDashboardPersonalTreinosEditarSlugRoute
  AuthenticatedPersonalDashboardPersonalTreinosModeloModeloIdRoute: typeof AuthenticatedPersonalDashboardPersonalTreinosModeloModeloIdRoute
  AuthenticatedPersonalDashboardPersonalTreinosPlanoPlanoIdRoute: typeof AuthenticatedPersonalDashboardPersonalTreinosPlanoPlanoIdRoute
}

const AuthenticatedPersonalRouteRouteChildren: AuthenticatedPersonalRouteRouteChildren =
  {
    AuthenticatedPersonalDashboardPersonalAcademiaRoute:
      AuthenticatedPersonalDashboardPersonalAcademiaRoute,
    AuthenticatedPersonalDashboardPersonalDesafiosRoute:
      AuthenticatedPersonalDashboardPersonalDesafiosRoute,
    AuthenticatedPersonalDashboardPersonalExerciciosRoute:
      AuthenticatedPersonalDashboardPersonalExerciciosRoute,
    AuthenticatedPersonalDashboardPersonalFinanceiroRoute:
      AuthenticatedPersonalDashboardPersonalFinanceiroRoute,
    AuthenticatedPersonalDashboardPersonalAlunosAlunoIdRoute:
      AuthenticatedPersonalDashboardPersonalAlunosAlunoIdRoute,
    AuthenticatedPersonalDashboardPersonalAvaliacaoAvaliacaoIdRoute:
      AuthenticatedPersonalDashboardPersonalAvaliacaoAvaliacaoIdRoute,
    AuthenticatedPersonalDashboardPersonalAvaliacoesAlunoIdRoute:
      AuthenticatedPersonalDashboardPersonalAvaliacoesAlunoIdRoute,
    AuthenticatedPersonalDashboardPersonalPersonaisPersonalIdRoute:
      AuthenticatedPersonalDashboardPersonalPersonaisPersonalIdRoute,
    AuthenticatedPersonalDashboardPersonalTreinosNovoPlanoRoute:
      AuthenticatedPersonalDashboardPersonalTreinosNovoPlanoRoute,
    AuthenticatedPersonalDashboardPersonalTreinosNovoTemplateRoute:
      AuthenticatedPersonalDashboardPersonalTreinosNovoTemplateRoute,
    AuthenticatedPersonalDashboardPersonalAlunosIndexRoute:
      AuthenticatedPersonalDashboardPersonalAlunosIndexRoute,
    AuthenticatedPersonalDashboardPersonalAvaliacoesIndexRoute:
      AuthenticatedPersonalDashboardPersonalAvaliacoesIndexRoute,
    AuthenticatedPersonalDashboardPersonalPersonaisIndexRoute:
      AuthenticatedPersonalDashboardPersonalPersonaisIndexRoute,
    AuthenticatedPersonalDashboardPersonalTreinosIndexRoute:
      AuthenticatedPersonalDashboardPersonalTreinosIndexRoute,
    AuthenticatedPersonalDashboardPersonalTreinosEditarSlugRoute:
      AuthenticatedPersonalDashboardPersonalTreinosEditarSlugRoute,
    AuthenticatedPersonalDashboardPersonalTreinosModeloModeloIdRoute:
      AuthenticatedPersonalDashboardPersonalTreinosModeloModeloIdRoute,
    AuthenticatedPersonalDashboardPersonalTreinosPlanoPlanoIdRoute:
      AuthenticatedPersonalDashboardPersonalTreinosPlanoPlanoIdRoute,
  }

const AuthenticatedPersonalRouteRouteWithChildren =
  AuthenticatedPersonalRouteRoute._addFileChildren(
    AuthenticatedPersonalRouteRouteChildren,
  )

interface AuthenticatedMeuTreinoRouteChildren {
  AuthenticatedMeuTreinoTreinoIdRoute: typeof AuthenticatedMeuTreinoTreinoIdRoute
}

const AuthenticatedMeuTreinoRouteChildren: AuthenticatedMeuTreinoRouteChildren =
  {
    AuthenticatedMeuTreinoTreinoIdRoute: AuthenticatedMeuTreinoTreinoIdRoute,
  }

const AuthenticatedMeuTreinoRouteWithChildren =
  AuthenticatedMeuTreinoRoute._addFileChildren(
    AuthenticatedMeuTreinoRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAcademiaRouteRoute: typeof AuthenticatedAcademiaRouteRouteWithChildren
  AuthenticatedAlunoRouteRoute: typeof AuthenticatedAlunoRouteRouteWithChildren
  AuthenticatedPersonalRouteRoute: typeof AuthenticatedPersonalRouteRouteWithChildren
  AuthenticatedAvaliacoesRoute: typeof AuthenticatedAvaliacoesRoute
  AuthenticatedDesafiosRoute: typeof AuthenticatedDesafiosRoute
  AuthenticatedMeuTreinoRoute: typeof AuthenticatedMeuTreinoRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedTreinosRoute: typeof AuthenticatedTreinosRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAcademiaRouteRoute: AuthenticatedAcademiaRouteRouteWithChildren,
  AuthenticatedAlunoRouteRoute: AuthenticatedAlunoRouteRouteWithChildren,
  AuthenticatedPersonalRouteRoute: AuthenticatedPersonalRouteRouteWithChildren,
  AuthenticatedAvaliacoesRoute: AuthenticatedAvaliacoesRoute,
  AuthenticatedDesafiosRoute: AuthenticatedDesafiosRoute,
  AuthenticatedMeuTreinoRoute: AuthenticatedMeuTreinoRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedTreinosRoute: AuthenticatedTreinosRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
